<a href="https://colab.research.google.com/github/nightshade97676-alt/rathinam-chatbot-replica/blob/main/merlin_divya_churn_predection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

customer churn predectioon

In [ ]:
import pandas as pd
import numpy as py
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("Telcom-Customer-Churn.csv")

Saving Telcom-Customer-Churn.csv to Telcom-Customer-Churn (6).csv


In [ ]:
# 1. Display first 5 records
df.head()

# 2. Display last 5 records
df.tail()

# 3. Display the shape
df.shape

# 4. Display information
df.info()

# 5. Display column names
df.columns.tolist()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [ ]:
target = "Churn"
print(target)

Churn


In [ ]:
# to view specific coulmn
df['Churn'].value_counts()

,count
Churn,
No,5174
Yes,1869


In [ ]:
# define the statisical summary
df.describe()

,SeniorCitizen,tenure,MonthlyCharges
count,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,64.761692
std,0.368612,24.559481,30.090047
min,0.000000,0.000000,18.250000
25%,0.000000,9.000000,35.500000
50%,0.000000,29.000000,70.350000
75%,0.000000,55.000000,89.850000
max,1.000000,72.000000,118.750000


In [ ]:
# Display unique names (only in categorical values)
df.gender.unique()

array(['Female', 'Male'], dtype=object)

data cleaning and preprocessing

In [ ]:
# to check duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
# to find null value or missing values
df.isnull().sum()

,0
customerID,0
gender,0
SeniorCitizen,0
Partner,0
Dependents,0
tenure,0
PhoneService,0
MultipleLines,0
InternetService,0
OnlineSecurity,0


ENCODING

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# to give categroical value
ctg = df.select_dtypes(include='object').columns
ctg

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges',
       'Churn'],
      dtype='object')

In [ ]:
le = LabelEncoder()

Data Preprocessing (Train Test Split)

Model Building

In [ ]:
from sklearn.model_selection import train_test_split
x = df[["tenure"]]
y = df["Churn"]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.3,random_state=42)
x_train
y_train

,Churn
1695,No
1095,No
3889,No
3667,No
2902,No
...,...
3772,Yes
5191,No
5226,No
5390,Yes


In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
# To display coefficients
model.coef_

array([[-0.03801196]])

In [ ]:
# display intercept

model.intercept_

array([-0.00072235])

In [ ]:
y_pred = model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
cm=confusion_matrix(y_pred,y_test)
cm

array([[1539,  574],
       [   0,    0]])

In [ ]:
report = classification_report(y_pred,y_test)
report

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


'              precision    recall  f1-score   support\n\n          No       1.00      0.73      0.84      2113\n         Yes       0.00      0.00      0.00         0\n\n    accuracy                           0.73      2113\n   macro avg       0.50      0.36      0.42      2113\nweighted avg       1.00      0.73      0.84      2113\n'